# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "update"
    commit-message:
      include: scope
      prefix: update

  # Update npm packages
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "@types/*"
        update-types:
          - "version-update:semver-patch"
    schedule:
      interval: "daily"
    labels:
      - "update"
    commit-message:
      include: scope
      prefix: update
