name: CI

on:
  pull_request:
    branches: ["master", "main"]

  push:
    branches: ["master", "main"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18"
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run lint
